(()=>{
const KEY='punpin-v2';
const defaults={xp:0,coins:0,streak:1,lastDay:'',missions:{color:0,math:0,puzzle:0},unlocked:['panda'],music:true,voice:true,plays:0};
let state={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')};
const rewards=[['panda','🐼',50],['hero','🦸',100],['crown','👑',150],['wings','🪽',200],['glasses','😎',300],['rocket','🚀',500]];
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const today=()=>new Date().toISOString().slice(0,10);
function dayCheck(){if(state.lastDay!==today()){state.streak=Math.max(1,state.streak+(state.lastDay?1:0));state.lastDay=today();save()}}
function tone(freq=600,d=.08,type='sine',vol=.05){if(!state.music)return;try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch(e){}}
function speak(text){if(!state.voice||!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='th-TH';u.rate=.9;u.pitch=1.15;speechSynthesis.speak(u)}
function sparkle(){const d=document.createElement('div');d.className='v2-spark';d.textContent=['⭐','✨','🎉','🌈'][Math.floor(Math.random()*4)];d.style.left=(20+Math.random()*60)+'vw';document.body.appendChild(d);setTimeout(()=>d.remove(),1100)}
function award(xp=10,coins=5,msg='เก่งมาก!'){state.xp+=xp;state.coins+=coins;state.plays++;rewards.forEach(r=>{if(state.xp>=r[2]&&!state.unlocked.includes(r[0]))state.unlocked.push(r[0])});save();render();tone(740,.09);setTimeout(()=>tone(980,.12),80);speak(msg);for(let i=0;i<8;i++)setTimeout(sparkle,i*55)}
function mission(kind){if(kind in state.missions){state.missions[kind]++;save();render()}}
function inject(){const css=document.createElement('style');css.textContent=`
.v2dock{position:fixed;right:18px;bottom:18px;z-index:60;display:flex;gap:9px}.v2fab{border:0;border-radius:18px;padding:11px 14px;background:#fff;box-shadow:0 12px 32px #4733802b;font:700 13px Mali,sans-serif;cursor:pointer}.v2fab:active{transform:scale(.94)}
.v2stats{display:flex;gap:7px;flex-wrap:wrap;margin-top:13px}.v2chip{background:#ffffff26;border:1px solid #ffffff42;border-radius:999px;padding:7px 11px;font-weight:700}.v2mission{margin-top:18px;display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.v2m{background:#fff;border-radius:18px;padding:11px;color:#433a69;box-shadow:0 8px 20px #39286b16;font-size:12px}.v2bar{height:7px;background:#eee9fa;border-radius:9px;margin-top:7px;overflow:hidden}.v2bar i{height:100%;display:block;background:linear-gradient(90deg,#ff6ea8,#7c5cff,#55c8ff)}
.v2modal{position:fixed;inset:0;z-index:100;background:#30285066;backdrop-filter:blur(8px);display:none;place-items:center;padding:18px}.v2modal.on{display:grid}.v2card{width:min(700px,96vw);max-height:86vh;overflow:auto;background:#fff;border-radius:32px;padding:24px;box-shadow:0 30px 80px #241b5160}.v2card h2{margin:0 0 5px}.v2close{float:right;border:0;background:#f1edfb;border-radius:14px;padding:9px 12px;cursor:pointer}.v2rewards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}.v2reward{border-radius:20px;background:#f8f5ff;padding:14px;text-align:center}.v2reward b{font-size:34px;display:block}.locked{filter:grayscale(1);opacity:.42}.v2-spark{position:fixed;bottom:15%;z-index:150;font-size:30px;pointer-events:none;animation:v2fly 1.1s ease-out forwards}@keyframes v2fly{to{transform:translateY(-55vh) rotate(25deg);opacity:0}}
@media(max-width:650px){.v2mission{grid-template-columns:1fr}.v2rewards{grid-template-columns:repeat(2,1fr)}.v2dock{right:10px;bottom:10px}}
`;document.head.appendChild(css);
const dock=document.createElement('div');dock.className='v2dock';dock.innerHTML='<button class="v2fab" id="v2reward">🎁 รางวัล</button><button class="v2fab" id="v2parent">👨‍👩‍👧 ผู้ปกครอง</button>';document.body.appendChild(dock);
const modal=document.createElement('div');modal.className='v2modal';modal.id='v2modal';modal.innerHTML='<div class="v2card"><button class="v2close" id="v2close">✕</button><div id="v2content"></div></div>';document.body.appendChild(modal);
document.getElementById('v2close').onclick=()=>modal.classList.remove('on');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('on')};
document.getElementById('v2reward').onclick=()=>showRewards();document.getElementById('v2parent').onclick=()=>showParent();
const hero=document.querySelector('.heroCopy');if(hero){const box=document.createElement('div');box.id='v2hero';hero.appendChild(box)}
}
function render(){const h=document.getElementById('v2hero');if(!h)return;const m=state.missions;h.innerHTML=`<div class="v2stats"><span class="v2chip">🏅 Lv.${1+Math.floor(state.xp/100)}</span><span class="v2chip">✨ ${state.xp} XP</span><span class="v2chip">🪙 ${state.coins}</span><span class="v2chip">🔥 ${state.streak} วัน</span></div><div class="v2mission"><div class="v2m">🎨 ระบายสี ${Math.min(m.color,1)}/1<div class="v2bar"><i style="width:${Math.min(m.color,1)*100}%"></i></div></div><div class="v2m">🧮 คณิต 5 ข้อ ${Math.min(m.math,5)}/5<div class="v2bar"><i style="width:${Math.min(m.math/5,1)*100}%"></i></div></div><div class="v2m">🧩 จิ๊กซอว์ ${Math.min(m.puzzle,1)}/1<div class="v2bar"><i style="width:${Math.min(m.puzzle,1)*100}%"></i></div></div></div>`}
function showRewards(){const c=document.getElementById('v2content');c.innerHTML=`<h2>🎁 ห้องรางวัล</h2><p>เล่นและเรียนรู้เพื่อปลดล็อกของสะสม</p><div class="v2rewards">${rewards.map(r=>`<div class="v2reward ${state.unlocked.includes(r[0])?'':'locked'}"><b>${r[1]}</b>${state.unlocked.includes(r[0])?'ปลดล็อกแล้ว':r[2]+' XP'}</div>`).join('')}</div>`;document.getElementById('v2modal').classList.add('on');tone(520,.08)}
function showParent(){const c=document.getElementById('v2content');c.innerHTML=`<h2>👨‍👩‍👧 Parent Area</h2><p>สรุปความก้าวหน้าบนอุปกรณ์เครื่องนี้</p><div class="v2rewards"><div class="v2reward"><b>✨</b>${state.xp} XP</div><div class="v2reward"><b>🎮</b>${state.plays} กิจกรรม</div><div class="v2reward"><b>🔥</b>${state.streak} วันต่อเนื่อง</div></div><p style="margin-top:18px"><button class="v2fab" id="voiceToggle">🗣️ เสียงพูด ${state.voice?'ON':'OFF'}</button> <button class="v2fab" id="musicToggle">🎵 เอฟเฟกต์ ${state.music?'ON':'OFF'}</button></p><small>ข้อมูลเก็บเฉพาะในเบราว์เซอร์นี้ ไม่มีการส่งข้อมูลเด็กออกไปภายนอก</small>`;document.getElementById('v2modal').classList.add('on');document.getElementById('voiceToggle').onclick=()=>{state.voice=!state.voice;save();showParent()};document.getElementById('musicToggle').onclick=()=>{state.music=!state.music;save();showParent()}}
function hook(){document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return; tone(360,.035,'sine',.025);const tx=t.textContent||'';if(/เสร็จ|สำเร็จ|รับดาว/.test(tx)){award(15,8,'เยี่ยมมาก ทำสำเร็จแล้ว');if(/ระบาย/.test(document.body.innerText))mission('color')}if(t.classList.contains('answer')&&t.classList.contains('good')){mission('math')}});const obs=new MutationObserver(()=>{const f=document.querySelector('.feedback');if(f&&/ถูก|เก่ง|เยี่ยม/.test(f.textContent)&&f.dataset.v2!=='1'){f.dataset.v2='1';mission('math');award(5,2,'ตอบถูก เก่งมาก')}});obs.observe(document.body,{subtree:true,childList:true,characterData:true})}
dayCheck();inject();render();hook();window.PunPinV2={award,mission,speak};setTimeout(()=>speak('สวัสดีจ้ะ มาเล่นและเรียนรู้กันนะ'),700);
})();