(()=>{
const $=s=>document.querySelector(s);let stage='kg',score=0,no=1,current=null;
const cfg={kg:{label:'อนุบาล',max:10,ops:['+','-'],visual:true},p1:{label:'ป.1',max:20,ops:['+','-'],visual:true},p2:{label:'ป.2',max:100,ops:['+','-'],visual:false},p3:{label:'ป.3',max:1000,ops:['+','-'],visual:false}};
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function make(){const c=cfg[stage],op=c.ops[rand(0,c.ops.length-1)];let a,b,ans;if(op==='+'){a=rand(stage==='kg'?0:1,Math.max(2,Math.floor(c.max*.7)));b=rand(0,c.max-a);ans=a+b}else{a=rand(1,c.max);b=rand(0,a);ans=a-b}return{a,b,op,ans}}
function choices(ans,max){const s=new Set([ans]);while(s.size<3){const d=stage==='p3'?rand(-80,80):stage==='p2'?rand(-15,15):rand(-5,5);const v=Math.max(0,Math.min(max,ans+d));s.add(v)}return[...s].sort(()=>Math.random()-.5)}
function visual(q){if(!cfg[stage].visual)return '';const emo=['🍎','⭐','🐻','🌼','🚗'][rand(0,4)];if(q.op==='+')return `<span>${emo.repeat(Math.min(q.a,10))}</span><b> + </b><span>${emo.repeat(Math.min(q.b,10))}</span>`;return `<span>${emo.repeat(Math.min(q.a,10))}</span><b> − ${q.b}</b>`}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='th-TH';u.rate=.85;speechSynthesis.speak(u)}catch(e){}}
function render(){current=make();const q=current;$('#questionNo').textContent='ข้อที่ '+no;$('#mathVisual').innerHTML=visual(q);$('#mathQuestion').textContent=`${q.a} ${q.op==='+'?'+':'−'} ${q.b} = ?`;$('#mathHint').textContent=stage==='kg'?'ลองนับภาพแล้วเลือกคำตอบ':stage==='p1'?'คิดทีละขั้น แล้วเลือกคำตอบที่ถูกต้อง':stage==='p2'?'ฝึกบวก–ลบจำนวนไม่เกิน 100':'ฝึกบวก–ลบจำนวนไม่เกิน 1,000';$('#mathFeedback').textContent='';$('#mathFeedback').className='mathFeedback';$('#mathAnswers').innerHTML=choices(q.ans,cfg[stage].max).map(x=>`<button class="answerBtn" data-k3-answer="${x}">${x}</button>`).join('')}
function init(){const tabs=$('.levelTabs');if(!tabs||!$('#mathAnswers'))return;tabs.innerHTML=Object.entries(cfg).map(([k,v])=>`<button class="levelBtn ${k==='kg'?'on':''}" data-k3-stage="${k}">${v.label}</button>`).join('');tabs.addEventListener('click',e=>{const k=e.target.dataset.k3Stage;if(!k)return;e.stopImmediatePropagation();stage=k;no=1;tabs.querySelectorAll('.levelBtn').forEach(b=>b.classList.toggle('on',b===e.target));render()},true);$('#mathAnswers').addEventListener('click',e=>{const b=e.target.closest('[data-k3-answer]');if(!b)return;e.stopImmediatePropagation();const v=+b.dataset.k3Answer;const good=v===current.ans;b.classList.add(good?'correct':'wrong');if(good){score+=10;$('#mathScore').textContent=score;$('#mathFeedback').textContent='🎉 ถูกต้อง เก่งมาก!';$('#mathFeedback').className='mathFeedback good';speak('ถูกต้อง เก่งมาก');setTimeout(()=>{no++;render()},700)}else{$('#mathFeedback').textContent='ลองอีกครั้งนะ 💪';$('#mathFeedback').className='mathFeedback try';speak('ลองอีกครั้งนะ')}},true);const sb=$('#mathSpeakBtn');if(sb)sb.addEventListener('click',e=>{e.stopImmediatePropagation();speak(`${current.a} ${current.op==='+'?'บวก':'ลบ'} ${current.b} เท่ากับเท่าไร`)},true);render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();