(()=>{
const $=s=>document.querySelector(s);let stage='kg',score=0,no=1,current=null;
const cfg={kg:{label:'อนุบาล',max:20,ops:['+','-'],visual:true},p1:{label:'ป.1',max:100,ops:['+','-'],visual:true},p2:{label:'ป.2',max:1000,ops:['+','-','*'],visual:false},p3:{label:'ป.3',max:1000,ops:['+','-','*','/'],visual:false}};
const gradeMap={k:'kg',p1:'p1',p2:'p2',p3:'p3'};
function selectedStage(){return gradeMap[localStorage.getItem('punpin_grade_v1')||'k']||'kg'}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function make(){const c=cfg[stage],op=c.ops[rand(0,c.ops.length-1)];let a,b,ans;if(op==='+'){a=rand(stage==='kg'?0:1,Math.max(2,Math.floor(c.max*.7)));b=rand(0,c.max-a);ans=a+b}else if(op==='-'){a=rand(1,c.max);b=rand(0,a);ans=a-b}else if(op==='*'){a=rand(2,stage==='p2'?5:12);b=rand(1,12);ans=a*b}else{b=rand(2,12);ans=rand(1,12);a=b*ans}return{a,b,op,ans}}
function choices(ans,max){const s=new Set([ans]);while(s.size<3){const d=stage==='p3'?rand(-30,30):stage==='p2'?rand(-15,15):stage==='p1'?rand(-10,10):rand(-5,5);const v=Math.max(0,Math.min(Math.max(max,ans+40),ans+d));s.add(v)}return[...s].sort(()=>Math.random()-.5)}
function visual(q){if(!cfg[stage].visual)return '';const emo=['🍎','⭐','🐻','🌼','🚗'][rand(0,4)];if(q.op==='+')return `<span>${emo.repeat(Math.min(q.a,10))}</span><b> + </b><span>${emo.repeat(Math.min(q.b,10))}</span>`;if(q.op==='-')return `<span>${emo.repeat(Math.min(q.a,10))}</span><b> − ${q.b}</b>`;return ''}
function speak(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='th-TH';u.rate=.85;speechSynthesis.speak(u)}catch(e){}}
function opText(op){return op==='+'?'+':op==='-'?'−':op==='*'?'×':'÷'}
function hint(){return stage==='kg'?'ลองนับภาพแล้วเลือกคำตอบ':stage==='p1'?'ฝึกบวก–ลบจำนวนไม่เกิน 100':stage==='p2'?'ฝึกบวก–ลบและคูณเบื้องต้น':'ฝึกบวก ลบ คูณ และหาร'}
function syncLevelBadge(){const tabs=$('.levelTabs');if(!tabs)return;tabs.innerHTML=`<button class="levelBtn on" type="button" style="grid-column:1/-1;cursor:default">🎒 ระดับ ${cfg[stage].label} · ระบบเลือกให้อัตโนมัติ</button>`;tabs.style.gridTemplateColumns='1fr'}
function render(){current=make();const q=current;$('#questionNo').textContent='ข้อที่ '+no;$('#mathVisual').innerHTML=visual(q);$('#mathQuestion').textContent=`${q.a} ${opText(q.op)} ${q.b} = ?`;$('#mathHint').textContent=hint();$('#mathFeedback').textContent='';$('#mathFeedback').className='mathFeedback';$('#mathAnswers').innerHTML=choices(q.ans,cfg[stage].max).map(x=>`<button class="answerBtn" data-k3-answer="${x}">${x}</button>`).join('')}
function syncGrade(reset=true){stage=selectedStage();if(reset){no=1;score=0;const sc=$('#mathScore');if(sc)sc.textContent='0'}syncLevelBadge();if($('#mathAnswers'))render()}
function init(){const tabs=$('.levelTabs');if(!tabs||!$('#mathAnswers'))return;stage=selectedStage();syncLevelBadge();$('#mathAnswers').addEventListener('click',e=>{const b=e.target.closest('[data-k3-answer]');if(!b)return;e.stopImmediatePropagation();const v=+b.dataset.k3Answer;const good=v===current.ans;b.classList.add(good?'correct':'wrong');if(good){score+=10;$('#mathScore').textContent=score;$('#mathFeedback').textContent='🎉 ถูกต้อง เก่งมาก!';$('#mathFeedback').className='mathFeedback good';speak('ถูกต้อง เก่งมาก');setTimeout(()=>{no++;render()},700)}else{$('#mathFeedback').textContent='ลองอีกครั้งนะ 💪';$('#mathFeedback').className='mathFeedback try';speak('ลองอีกครั้งนะ')}},true);const sb=$('#mathSpeakBtn');if(sb)sb.addEventListener('click',e=>{e.stopImmediatePropagation();const o=current.op==='+'?'บวก':current.op==='-'?'ลบ':current.op==='*'?'คูณ':'หาร';speak(`${current.a} ${o} ${current.b} เท่ากับเท่าไร`)},true);document.addEventListener('punpin:grade',()=>syncGrade(true));render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();